config/routes.rb
Rails.application.routes.draw do
	resources :articles
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def new
		@name = "qiandiao"
		@email = "sha_moon@126.com"
	end
	def index
		@articles = Article.all
	end
	def create
	end
	def show
		@article = Article.first
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<h1>文章列表</h1>
 
<table>
  <tr>
    <th>Title:</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
			<td><%= link_to article.title, article_path(article) %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>new</h1>
<%= @name %><br>
<%= @email %>

app/views/articles/show.html.erb
<h3>
<strong>Title:</strong>
<%= @article.title %>
</h3>

<p>
<strong>Text:</strong>
<%= @article.text %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>